name: Frontend CI

on:
  push:
    branches: ["main"]
    paths:
      - "almirante-tamandare-frontend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "almirante-tamandare-frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # LTS recomendada

    defaults:
      run:
        working-directory: almirante-tamandare-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: almirante-tamandare-frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build --if-present

      - name: Run tests
        run: npm test --if-present
